@echo off
cd C:\Users\Administrator.OS-201709041456\Desktop\ACP_Fuse//csv/
python IndenpendenceTest.py RFAAC(N=1).model AAC(N=1).csv
python IndenpendenceTest.py RFAAC(N=2).model AAC(N=2).csv
python IndenpendenceTest.py RF188D.model 188D.csv
python IndenpendenceTest.py RF400D.model 400D.csv
python IndenpendenceTest.py RFCKSAAP.model CKSAAP.csv
python IndenpendenceTest.py RFCKSAAGP.model CKSAAGP.csv
python IndenpendenceTest.py RFCTD.model CTD.csv
python IndenpendenceTest.py RFCTDC.model CTDC.csv
python IndenpendenceTest.py RFCTDD.model CTDD.csv
python IndenpendenceTest.py RFCTDT.model CTDT.csv
python IndenpendenceTest.py RFCTriad.model CTriad.csv
python IndenpendenceTest.py RFDDE.model DDE.csv
python IndenpendenceTest.py RFDPC.model DPC.csv
python IndenpendenceTest.py RFGAAC.model GAAC.csv
python IndenpendenceTest.py RFGDPC.model GDPC.csv
python IndenpendenceTest.py RFGTPC.model GTPC.csv
python IndenpendenceTest.py RFKSCTriad.model KSCTriad.csv
python IndenpendenceTest.py RFTPC.model TPC.csv
python IndenpendenceTest.py RFAACNT(1).model AAC(NT1).csv
python IndenpendenceTest.py RFAACNT(2).model AAC(NT2).csv
python IndenpendenceTest.py RFAACNT(3).model AAC(NT3).csv
python IndenpendenceTest.py RFAACNT(4).model AAC(NT4).csv
python IndenpendenceTest.py RFAACNT(5).model AAC(NT5).csv
python IndenpendenceTest.py RFAACNT(6).model AAC(NT6).csv
python IndenpendenceTest.py RFAACNT(7).model AAC(NT7).csv
python IndenpendenceTest.py RFAACNT(8).model AAC(NT8).csv
python IndenpendenceTest.py RFAACNT(9).model AAC(NT9).csv
python IndenpendenceTest.py RFAACNT(10).model AAC(NT10).csv
python IndenpendenceTest.py RFAAINDEXNT(1).model AAINDEX(NT1).csv
python IndenpendenceTest.py RFAAINDEXNT(2).model AAINDEX(NT2).csv
python IndenpendenceTest.py RFAAINDEXNT(3).model AAINDEX(NT3).csv
python IndenpendenceTest.py RFAAINDEXNT(4).model AAINDEX(NT4).csv
python IndenpendenceTest.py RFAAINDEXNT(5).model AAINDEX(NT5).csv
python IndenpendenceTest.py RFAAINDEXNT(6).model AAINDEX(NT6).csv
python IndenpendenceTest.py RFAAINDEXNT(7).model AAINDEX(NT7).csv
python IndenpendenceTest.py RFAAINDEXNT(8).model AAINDEX(NT8).csv
python IndenpendenceTest.py RFAAINDEXNT(9).model AAINDEX(NT9).csv
python IndenpendenceTest.py RFAAINDEXNT(10).model AAINDEX(NT10).csv
python IndenpendenceTest.py RFBIT20NT(1).model BIT20(NT1).csv
python IndenpendenceTest.py RFBIT20NT(2).model BIT20(NT2).csv
python IndenpendenceTest.py RFBIT20NT(3).model BIT20(NT3).csv
python IndenpendenceTest.py RFBIT20NT(4).model BIT20(NT4).csv
python IndenpendenceTest.py RFBIT20NT(5).model BIT20(NT5).csv
python IndenpendenceTest.py RFBIT20NT(6).model BIT20(NT6).csv
python IndenpendenceTest.py RFBIT20NT(7).model BIT20(NT7).csv
python IndenpendenceTest.py RFBIT20NT(8).model BIT20(NT8).csv
python IndenpendenceTest.py RFBIT20NT(9).model BIT20(NT9).csv
python IndenpendenceTest.py RFBIT20NT(10).model BIT20(NT10).csv
python IndenpendenceTest.py RFBIT21NT(1).model BIT21(NT1).csv
python IndenpendenceTest.py RFBIT21NT(2).model BIT21(NT2).csv
python IndenpendenceTest.py RFBIT21NT(3).model BIT21(NT3).csv
python IndenpendenceTest.py RFBIT21NT(4).model BIT21(NT4).csv
python IndenpendenceTest.py RFBIT21NT(5).model BIT21(NT5).csv
python IndenpendenceTest.py RFBIT21NT(6).model BIT21(NT6).csv
python IndenpendenceTest.py RFBIT21NT(7).model BIT21(NT7).csv
python IndenpendenceTest.py RFBIT21NT(8).model BIT21(NT8).csv
python IndenpendenceTest.py RFBIT21NT(9).model BIT21(NT9).csv
python IndenpendenceTest.py RFBIT21NT(10).model BIT21(NT10).csv
python IndenpendenceTest.py RFBLOSUM62NT(1).model BLOSUM62(NT1).csv
python IndenpendenceTest.py RFBLOSUM62NT(2).model BLOSUM62(NT2).csv
python IndenpendenceTest.py RFBLOSUM62NT(3).model BLOSUM62(NT3).csv
python IndenpendenceTest.py RFBLOSUM62NT(4).model BLOSUM62(NT4).csv
python IndenpendenceTest.py RFBLOSUM62NT(5).model BLOSUM62(NT5).csv
python IndenpendenceTest.py RFBLOSUM62NT(6).model BLOSUM62(NT6).csv
python IndenpendenceTest.py RFBLOSUM62NT(7).model BLOSUM62(NT7).csv
python IndenpendenceTest.py RFBLOSUM62NT(8).model BLOSUM62(NT8).csv
python IndenpendenceTest.py RFBLOSUM62NT(9).model BLOSUM62(NT9).csv
python IndenpendenceTest.py RFBLOSUM62NT(10).model BLOSUM62(NT10).csv
python IndenpendenceTest.py RFITNT(1).model IT(NT1).csv
python IndenpendenceTest.py RFITNT(2).model IT(NT2).csv
python IndenpendenceTest.py RFITNT(3).model IT(NT3).csv
python IndenpendenceTest.py RFITNT(4).model IT(NT4).csv
python IndenpendenceTest.py RFITNT(5).model IT(NT5).csv
python IndenpendenceTest.py RFITNT(6).model IT(NT6).csv
python IndenpendenceTest.py RFITNT(7).model IT(NT7).csv
python IndenpendenceTest.py RFITNT(8).model IT(NT8).csv
python IndenpendenceTest.py RFITNT(9).model IT(NT9).csv
python IndenpendenceTest.py RFITNT(10).model IT(NT10).csv
python IndenpendenceTest.py RFOLPNT(1).model OLP(NT1).csv
python IndenpendenceTest.py RFOLPNT(2).model OLP(NT2).csv
python IndenpendenceTest.py RFOLPNT(3).model OLP(NT3).csv
python IndenpendenceTest.py RFOLPNT(4).model OLP(NT4).csv
python IndenpendenceTest.py RFOLPNT(5).model OLP(NT5).csv
python IndenpendenceTest.py RFOLPNT(6).model OLP(NT6).csv
python IndenpendenceTest.py RFOLPNT(7).model OLP(NT7).csv
python IndenpendenceTest.py RFOLPNT(8).model OLP(NT8).csv
python IndenpendenceTest.py RFOLPNT(9).model OLP(NT9).csv
python IndenpendenceTest.py RFOLPNT(10).model OLP(NT10).csv
python IndenpendenceTest.py RFZSCALENT(1).model ZSCALE(NT1).csv
python IndenpendenceTest.py RFZSCALENT(2).model ZSCALE(NT2).csv
python IndenpendenceTest.py RFZSCALENT(3).model ZSCALE(NT3).csv
python IndenpendenceTest.py RFZSCALENT(4).model ZSCALE(NT4).csv
python IndenpendenceTest.py RFZSCALENT(5).model ZSCALE(NT5).csv
python IndenpendenceTest.py RFZSCALENT(6).model ZSCALE(NT6).csv
python IndenpendenceTest.py RFZSCALENT(7).model ZSCALE(NT7).csv
python IndenpendenceTest.py RFZSCALENT(8).model ZSCALE(NT8).csv
python IndenpendenceTest.py RFZSCALENT(9).model ZSCALE(NT9).csv
python IndenpendenceTest.py RFZSCALENT(10).model ZSCALE(NT10).csv
python IndenpendenceTest.py RFAACNTCT(5).model AAC(NTCT5).csv
python IndenpendenceTest.py RFAACNTCT(6).model AAC(NTCT6).csv
python IndenpendenceTest.py RFAACNTCT(7).model AAC(NTCT7).csv
python IndenpendenceTest.py RFAACNTCT(8).model AAC(NTCT8).csv
python IndenpendenceTest.py RFAACNTCT(9).model AAC(NTCT9).csv
python IndenpendenceTest.py RFAACNTCT(10).model AAC(NTCT10).csv
python IndenpendenceTest.py RFGAACNTCT(5).model GAAC(NTCT5).csv
python IndenpendenceTest.py RFGAACNTCT(6).model GAAC(NTCT6).csv
python IndenpendenceTest.py RFGAACNTCT(7).model GAAC(NTCT7).csv
python IndenpendenceTest.py RFGAACNTCT(8).model GAAC(NTCT8).csv
python IndenpendenceTest.py RFGAACNTCT(9).model GAAC(NTCT9).csv
python IndenpendenceTest.py RFGAACNTCT(10).model GAAC(NTCT10).csv
python IndenpendenceTest.py RFGAP(g=1).model GAP(g=1).csv
python IndenpendenceTest.py RFGAP(g=2).model GAP(g=2).csv
python IndenpendenceTest.py RFGAP(g=3).model GAP(g=3).csv
python IndenpendenceTest.py RFGAP(g=4).model GAP(g=4).csv
exit